[package]
name = "ostfalia-thesis"
version = "0.2.3"
compiler = "0.13.1"
authors = [
  "Silvan Zahno <https://github.com/tschinz>",
  "Rémi Heredero <https://github.com/Klagarge>",
  "HEI-Vs <https://synd.hevs.io>",
]
repository = "https://github.com/0815sailsman/ostfalia-vw-typst-template"
#homepage = "https://synd.hevs.io"
license = "MIT"
description = "A thesis template for a bachelors thesis at the Ostfalia Hochschule für angewandte Wissenschaften, faculty informatics."
entrypoint = "lib/template-thesis.typ"
categories = ["thesis", "report", "paper"]
disciplines = ["engineering", "computer-science", "education"]
keywords = [
  "Thesis",
  "Report",
  "Project",
  "University",
  "Ostfalia",
]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
